version: 2

jobs:
  build:
    working_directory: /tmp
    docker:
      - image: cimg/base:stable
    steps:
      # 1) Install Nikto
      - run:
          name: Install Nikto
          command: |
            sudo apt-get update
            sudo apt-get install -y nikto

      # 2) Run Nikto
      - run:
          name: Run Nikto
          command: |
            nikto -h "https://dast-sast-test.onrender.com" -output /tmp/nikto_report.txt

      # 3) Create the “dummy artifacts” (as shown in CircleCI’s docs)
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1
            mkdir /tmp/artifacts
            echo "my artifact files in a dir" > /tmp/artifacts/art-2

      # 4) Store artifacts (two from the docs, one from Nikto)
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts

      - store_artifacts:
          path: /tmp/nikto_report.txt
          destination: nikto-report

workflows:
  version: 2
  build_wf:
    jobs:
      - build
