version: 2.1

jobs:
  nikto-scan:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install Nikto
          command: |
            sudo apt-get update
            sudo apt-get install -y nikto

      - run:
          name: Run Nikto
          command: |
            nikto -h "https://dast-sast-test.onrender.com" -output nikto_report.txt

      - run:
          name: Check that report exists
          command: |
            echo "Listing files in current dir:"
            ls -la
            echo "Content of nikto_report.txt"
            cat nikto_report.txt

      - store_artifacts:
          path: nikto_report.txt
          destination: nikto_reports

workflows:
  nikto_manual:
    jobs:
      - nikto-scan:
